### ISSUE TITLE
null value 

### ISSUE THREAD

**Issue by pradeep8892** [Jhuster/YUVDroidTools#2]
byte[] rgb565 = FFConverter.process(width, height, format, width, height, FFConverter.CV_FMT_RGB565,
                FFConverter.CV_ALG_FAST_BILINEAR, data, length);

i am getting null rgb565 array.

**Comment by Jhuster** [comment]
@pradeep14581 any error logs ?

**Comment by pradeep8892** [comment]
FATAL EXCEPTION: main
                                                                           Process: com.jhuster.yuvdroidtools, PID: 24371
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jhuster.yuvdroidtools/com.jhuster.yuvdroidtools.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                               at android.os.Looper.loop(Looper.java:207)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5769)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                            Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                               at java.nio.ByteArrayBuffer.<init>(ByteArrayBuffer.java:37)
                                                                               at java.nio.ByteBuffer.wrap(ByteBuffer.java:90)
                                                                               at com.jhuster.yuvdroidtools.MainActivity.displayImage(MainActivity.java:148)
                                                                               at com.jhuster.yuvdroidtools.MainActivity.onCreate(MainActivity.java:70)
                                                                               at android.app.Activity.performCreate(Activity.java:6583)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2531)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:207) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5769) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
08-30 16:21:33.177 24371-24380/com.jhuster.yuvdroidtools I/art: Debugger is no longer active
